/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#e9e8e7",
        "on-primary-fixed": "#3a0b00",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-container": "#636262",
        "primary-container": "#d43f00",
        "on-tertiary": "#ffffff",
        "surface-bright": "#fbf9f9",
        "on-surface": "#1b1c1c",
        "on-primary-fixed-variant": "#852400",
        "primary-fixed": "#ffdbd0",
        "surface-dim": "#dbdad9",
        "surface-tint": "#ae3200",
        "tertiary-container": "#737575",
        "primary-fixed-dim": "#ffb59e",
        "on-tertiary-fixed": "#1a1c1c",
        "surface": "#fbf9f9",
        "secondary-container": "#e2dfde",
        "on-error-container": "#93000a",
        "background": "#fbf9f9",
        "inverse-primary": "#ffb59e",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-container": "#fcfcfc",
        "on-background": "#1b1c1c",
        "outline": "#907066",
        "surface-container": "#efeded",
        "on-primary": "#ffffff",
        "primary": "#a93100",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "secondary": "#5f5e5e",
        "surface-variant": "#e3e2e2",
        "inverse-on-surface": "#f2f0f0",
        "on-secondary-fixed-variant": "#474746",
        "on-tertiary-fixed-variant": "#454747",
        "surface-container-low": "#f5f3f3",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-surface-variant": "#5b4038",
        "surface-container-lowest": "#ffffff",
        "surface-panel": "#fbf9f9",
        "tertiary": "#5b5c5c",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "outline-variant": "#e4beb3",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#303031",
        "surface-container-highest": "#e3e2e2",
        "on-secondary-fixed": "#1c1b1b"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        none: "0px",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "24px",
        "stack-sm": "8px",
        unit: "4px",
        "stack-lg": "32px",
        "stack-md": "16px",
        "margin-page": "48px",
        "container-max": "1440px"
      },
      fontFamily: {
        "display-lg": ["Space Grotesk", "sans-serif"],
        "label-xs": ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Grotesk", "sans-serif"],
        sans: ["Hanken Grotesk", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        brick: ["Space Grotesk", "sans-serif"],
        "headline-xl": ["Space Grotesk", "sans-serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "data-tabular": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Space Grotesk", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "80px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "label-xs": ["11px", { lineHeight: "16px", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "data-tabular": ["12px", { lineHeight: "1.2", fontWeight: "500" }],
        "label-caps": ["10px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "600" }]
      }
    }
  },
  plugins: [
    require("@tailwindcss/forms"),
  ]
}
